services:
  # --- DATABASE ---
  db:
    image: mysql:8.0
    container_name: music_web_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306" # Map ra port 3307 để không đụng MySQL trên máy thật
    volumes:
      - mysql_data:/var/lib/mysql
      # Dòng 2 (MỚI): Map file SQL để tự động import
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mongo:
    image: mongo:6
    container_name: music_web_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # --- BACKEND ---
  server:
    build: ./Server
    container_name: music_web_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy
    env_file:
      - .env
    # --- CẤU HÌNH TỰ ĐỘNG CẬP NHẬT CODE (HOT RELOAD) ---
    volumes:
      - ./Server:/app
      - /app/node_modules
      - ./Server/src/public:/app/src/public
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- AI SERVICE ---
  ai_service:
    build: ./AI_Services
    container_name: music_web_ai
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./AI_Services:/app
      - /app/__pycache__
    command: python src/api/server.py

  # --- FRONTEND ---
  ui:
    build: ./UI
    container_name: music_web_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_healthy
    # --- CẤU HÌNH TỰ ĐỘNG CẬP NHẬT CODE (HOT RELOAD) ---
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=http://server:5000
    volumes:
      - ./UI:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  mysql_data:
  mongo_data:
